#nullable disable

using System.Reflection;

namespace ECommons.ExcelServices;

public enum TerritoryIntendedUseEnum : uint
{
    [Obfuscation] [CommonlyUsed] City_Area = 0,
    [Obfuscation][CommonlyUsed] Open_World = 1,
    [Obfuscation][CommonlyUsed] Inn = 2,
    [Obfuscation][CommonlyUsed] Dungeon = 3,
    [Obfuscation][CommonlyUsed] Variant_Dungeon = 4,
    [Obfuscation] Gaol = 5,
    [Obfuscation] Starting_Area = 6,
    [Obfuscation] Quest_Area = 7,
    [Obfuscation][CommonlyUsed] Alliance_Raid = 8,
    [Obfuscation] Quest_Battle = 9,
    [Obfuscation][CommonlyUsed] Trial = 10,
    [Obfuscation] Quest_Area_2 = 12,
    [Obfuscation][CommonlyUsed] Residential_Area = 13,
    [Obfuscation][CommonlyUsed] Housing_Instances = 14,
    [Obfuscation] Quest_Area_3 = 15,
    [Obfuscation] Raid = 16,
    [Obfuscation][CommonlyUsed] Raid_2 = 17,
    [Obfuscation] Frontline = 18,
    [Obfuscation] Chocobo_Square = 20,
    [Obfuscation] Restoration_Event = 21,
    [Obfuscation] Sanctum = 22,
    [Obfuscation] Gold_Saucer = 23,
    [Obfuscation] Lord_of_Verminion = 25,
    [Obfuscation] Diadem = 26,
    [Obfuscation] Hall_of_the_Novice = 27,
    [Obfuscation] Crystalline_Conflict = 28,
    [Obfuscation] Quest_Battle_2 = 29,
    [Obfuscation] Barracks = 30,
    [Obfuscation][CommonlyUsed] Deep_Dungeon = 31,
    [Obfuscation] Seasonal_Event = 32,
    [Obfuscation] Treasure_Map_Duty = 33,
    [Obfuscation] Seasonal_Event_Duty = 34,
    [Obfuscation] Battlehall = 35,
    [Obfuscation] Crystalline_Conflict_2 = 37,
    [Obfuscation] Diadem_2 = 38,
    [Obfuscation] Rival_Wings = 39,
    [Obfuscation] Unknown_1 = 40,
    [Obfuscation][CommonlyUsed] Eureka = 41,
    [Obfuscation] Seasonal_Event_2 = 43,
    [Obfuscation] Leap_of_Faith = 44,
    [Obfuscation] Masked_Carnivale = 45,
    [Obfuscation] Ocean_Fishing = 46,
    [Obfuscation] Diadem_3 = 47,
    [Obfuscation][CommonlyUsed] Bozja = 48,
    [Obfuscation][CommonlyUsed] Island_Sanctuary = 49,
    [Obfuscation] Battlehall_2 = 50,
    [Obfuscation] Battlehall_3 = 51,
    [Obfuscation][CommonlyUsed] Large_Scale_Raid = 52,
    [Obfuscation][CommonlyUsed] Large_Scale_Savage_Raid = 53,
    [Obfuscation] Quest_Area_4 = 54,
    [Obfuscation] Tribal_Instance = 56,
    [Obfuscation][CommonlyUsed] Criterion_Duty = 57,
    [Obfuscation][CommonlyUsed] Criterion_Savage_Duty = 58,
    [Obfuscation] Blunderville = 59,
    [Obfuscation][CommonlyUsed] Occult_Crescent = 61,
}
