//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommons.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECommons.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate via Cryptocurrency.
        /// </summary>
        internal static string Context_CryptoDonation {
            get {
                return ResourceManager.GetString("Context_CryptoDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore other NightmareXIV plugins.
        /// </summary>
        internal static string Context_ExploreOtherPlugins {
            get {
                return ResourceManager.GetString("Context_ExploreOtherPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join NightmareXIV Discord.
        /// </summary>
        internal static string Context_JoinDiscord {
            get {
                return ResourceManager.GetString("Context_JoinDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate one-time via Ko-Fi.
        /// </summary>
        internal static string Context_OneTimeDonate {
            get {
                return ResourceManager.GetString("Context_OneTimeDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe on Patreon.
        /// </summary>
        internal static string Context_Subscribe {
            get {
                return ResourceManager.GetString("Context_Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Patreon.
        /// </summary>
        internal static string JoinPatreon {
            get {
                return ResourceManager.GetString("JoinPatreon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like this plugin, please consider supporting it via NightmareXIV Patreon or via other means! This will help the developer to keep it updated and maintained. And you will get additional benefits, such as priority support, access to private plugins and priority feature requests as well.
        ///
        ///Left click - to go to Patreon;
        ///Right click - see all options.
        /// </summary>
        internal static string PatreonButtonTooltip {
            get {
                return ResourceManager.GetString("PatreonButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like this plugin, please consider supporting it.
        ///
        ///Left click - to go to Patreon;
        ///Right click - see other options.
        /// </summary>
        internal static string SmallPatreonButtonTooltip {
            get {
                return ResourceManager.GetString("SmallPatreonButtonTooltip", resourceCulture);
            }
        }
    }
}
